Repository localleon/barco-slm-network, pull requests merged in 2019-10, with the labels that each got.

#17 Update README.md
  README.md
Labels: Hacktoberfest, documentation

#16 #14: Add OpenAPI docs
  go/api/openapi.json
  go/api/openapi.yaml
Labels: Hacktoberfest, enhancement

#18 Detailed OpenAPI Specification
  README.md
  go/api/openapi.json
  go/api/openapi.yaml
Labels: documentation
